name: SnowballFight
version: '1.0.0'
main: org.tomo25.snowballfight.SnowballFight
api-version: '1.20'

commands:
  snowballfightsetspawn:
    description: 赤チームと青チームのスタート地点を決めるコマンド
    usage: /snowballfightsetspawn <Blue|Red>
    aliases:
      - sballsetspawn
  snowballfighttime:
    description: ゲームの時間を変更するコマンド
    usage: /snowballfighttime <time>
    aliases:
      - sballtime
  snowballfightstart:
    description: ゲームを始めるコマンド
    usage: /snowballfightstart
    aliases:
      - sballstart
  snowballfightteam:
    description:  チームを分けるコマンド
    usage: /snowballfightteam <teamset|addplayer> <Red|Blue>
    aliases:
      - sbllteam
