name: SnowballFight
version: '1.0.0'
main: org.tomo25.snowballfight.SnowballFight
api-version: '1.20'

commands:
  setspawn:
    description: 赤チームと青チームのスタート地点を決めるコマンド
    usage: /setspawn <Blue|Red>
    aliases:
      - sballsetspawn
  settime:
    description: ゲームの時間を変更するコマンド
    usage: /settime <time>
    aliases:
      - sballtime
  start:
    description: ゲームを始めるコマンド
    usage: /start
    aliases:
      - sballstart
  team:
    description:  チームを分けるコマンド
    usage: /team <teamset|addplayer> <Red|Blue>
    aliases:
      - sbllteam
