name: SnowballFight
version: '${project.version}'
main: org.tomo25.snowballfight.SnowballFight
api-version: '1.20'

commands:
  snowballfightsetspawn:
    description: 赤チームと青チームのスタート地点を決めるコマンド
    usage: /<command> [Blue|Red]
    aliases:
      - sballspawn
  snowballfighttime:
    description: ゲームの時間を変更するコマンド
    usage: /<command> [time]
    aliases:
      - sballtime
  snowballfightstart:
    description: ゲームを始めるコマンド
    usage: /<command> [start]
    aliases:
      - sballstart
  snowballfightteam:
    description:  チームを分けるコマンド
    usage: /<command> [teamset|addplayer] [Red|Blue]
    aliases:
      - sbllteam
