name: SnowballFight
version: '${project.version}'
main: org.tomo25.snowballfight.SnowballFight
api-version: '1.20'

commands:
  snowballfighttime:
    description: ゲームの時間を変更するコマンド
    usage: /<command> [time]
    aliases:
      - sballtime
  snowballfightstart:
    description: ゲームを始めるコマンド
    usage: /<command>
    aliases:
      - sballstart
  snowballfightteam:
    description:  チームを分けるコマンド
    usage: /<command>
    aliases:
      - sbllteam